### ISSUE TITLE
Make a realease

### ISSUE THREAD

**Issue by Chris2011** [rcarmo/netbeans-clojure#4]
Hi,

please make a first release, if it is still usable so you can create a NBM file and add it to the plugin portal of NetBeans. Thx.

Regards

Chris

**Comment by rcarmo** [comment]
Hello there,

I no longer work with NetBeans (sadly, to a degree), so I cannot ensure I'll be able to do so. 

There were a few forks, you might want to check one of them for more updated code.

Thanks!

**Comment by Chris2011** [comment]
Ok, no problem. I will do it by my own, I mean the release and release ready ^^. Can you tell me how far the progress of this plugin was? Is it release ready?

**Comment by Vitexus** [comment]
Compiled today under Netbeans 11.3 / java11

[org-clojure.nbm.gz](https://github.com/rcarmo/netbeans-clojure/files/4224011/org-clojure.nbm.gz)

It force disabling most of other custom plugins but is usable.

**Comment by rcarmo** [comment]
Thanks!
